{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "  warnings.warn(msg, UserWarning)\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\n",
      "numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\n",
      "numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\n",
      "numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\n",
      "numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\n",
      "can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\n",
      "numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\n",
      "/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\n",
      "can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from src.conf.config import CONFIG\n",
    "from src.tune.tune_experiment import (\n",
    "    TuneReportCallback, CheckpointCallback,\n",
    "    train_tune_checkpoint, tune_pbt\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/leos/.local/lib/python3.6/site-packages/ray/resource_spec.py:310: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/proc/driver/nvidia/gpus/0000:01:00.0/information' mode='r' encoding='UTF-8'>\n",
      "\n",
      "2020-09-28 20:40:25,242\tINFO resource_spec.py:231 -- Starting Ray with 15.19 GiB memory available for workers and up to 7.6 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:746: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/redis-shard_0.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:746: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/redis-shard_0.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:746: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/redis.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:746: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/redis.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:748: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/gcs_server.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:748: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/gcs_server.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:750: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/monitor.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:750: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/monitor.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "2020-09-28 20:40:25,830\tINFO services.py:1193 -- View the Ray dashboard at \u001b[1m\u001b[32mlocalhost:8265\u001b[39m\u001b[22m\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:755: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/dashboard.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:755: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/dashboard.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:763: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/plasma_store.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:763: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/plasma_store.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:764: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/raylet.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:764: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/raylet.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:765: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/reporter.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:765: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/reporter.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:768: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/log_monitor.out' mode='a' encoding='utf-8'>\n",
      "\n",
      "/home/leos/.local/lib/python3.6/site-packages/ray/node.py:768: ResourceWarning:\n",
      "\n",
      "unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/log_monitor.err' mode='a' encoding='utf-8'>\n",
      "\n",
      "2020-09-28 20:40:26,151\tWARNING experiment.py:215 -- No name detected on trainable. Using DEFAULT.\n",
      "2020-09-28 20:40:26,152\tWARNING registry.py:64 -- Detected unknown callable for trainable. Converting to class.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 7.0/31.2 GiB<br>PopulationBasedTraining: 0 checkpoints, 0 perturbs<br>Resources requested: 1/12 CPUs, 1/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (2 PENDING, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m   warnings.warn(msg, UserWarning)\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:959: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-0aba8166ef5a732502a3068ceb575910f8d557df-0100.out' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:963: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-0aba8166ef5a732502a3068ceb575910f8d557df-0100.err' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m GPU available: True, used: True\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m TPU available: False, using: 0 TPU cores\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m CUDA_VISIBLE_DEVICES: [0]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m   | Name  | Type             | Params\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m -------------------------------------------\n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m 0 | model | Unet             | 31 M  \n",
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m 1 | CE    | CrossEntropyLoss | 0     \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/checkpoint_591/checkpoint\n",
      "Result for DEFAULT_b15f3_00000:\n",
      "  avg_val_accuracy: 0.938840155065388\n",
      "  avg_val_loss: 0.15237843990325928\n",
      "  date: 2020-09-28_20-46-23\n",
      "  done: false\n",
      "  experiment_id: b8813f7a5a7546afa30ed572aa19d414\n",
      "  experiment_tag: '0'\n",
      "  hostname: lx9-304-12646\n",
      "  iterations_since_restore: 1\n",
      "  node_ip: 192.168.100.11\n",
      "  pid: 18258\n",
      "  should_checkpoint: true\n",
      "  time_since_restore: 354.32049775123596\n",
      "  time_this_iter_s: 354.32049775123596\n",
      "  time_total_s: 354.32049775123596\n",
      "  timestamp: 1601315183\n",
      "  timesteps_since_restore: 0\n",
      "  training_iteration: 1\n",
      "  trial_id: b15f3_00000\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 9.8/31.2 GiB<br>PopulationBasedTraining: 0 checkpoints, 0 perturbs<br>Resources requested: 1/12 CPUs, 1/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (2 PENDING, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc                 </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th><th style=\"text-align: right;\">  avg_val_loss</th><th style=\"text-align: right;\">  avg_val_accuracy</th><th style=\"text-align: right;\">  training_iteration</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>RUNNING </td><td>192.168.100.11:18258</td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.152378</td><td style=\"text-align: right;\">           0.93884</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>PENDING </td><td>                    </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">              </td><td style=\"text-align: right;\">                  </td><td style=\"text-align: right;\">                    </td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>PENDING </td><td>                    </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">              </td><td style=\"text-align: right;\">                  </td><td style=\"text-align: right;\">                    </td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18258)\u001b[0m 2020-09-28 20:46:24,035\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m   warnings.warn(msg, UserWarning)\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:959: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-a9151eb23782899aeb13f9528b48d4470d104a75-0100.out' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:963: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-a9151eb23782899aeb13f9528b48d4470d104a75-0100.err' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m GPU available: True, used: True\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m TPU available: False, using: 0 TPU cores\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m CUDA_VISIBLE_DEVICES: [0]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m   | Name  | Type             | Params\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m -------------------------------------------\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m 0 | model | Unet             | 31 M  \n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m 1 | CE    | CrossEntropyLoss | 0     \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/checkpoint_591/checkpoint\n",
      "Result for DEFAULT_b15f3_00001:\n",
      "  avg_val_accuracy: 0.9418006460577065\n",
      "  avg_val_loss: 0.14329200983047485\n",
      "  date: 2020-09-28_20-52-18\n",
      "  done: false\n",
      "  experiment_id: 8c09b2b98a6642de9c7ee327f7543f02\n",
      "  experiment_tag: '1'\n",
      "  hostname: lx9-304-12646\n",
      "  iterations_since_restore: 1\n",
      "  node_ip: 192.168.100.11\n",
      "  pid: 18265\n",
      "  should_checkpoint: true\n",
      "  time_since_restore: 351.2957224845886\n",
      "  time_this_iter_s: 351.2957224845886\n",
      "  time_total_s: 351.2957224845886\n",
      "  timestamp: 1601315538\n",
      "  timesteps_since_restore: 0\n",
      "  training_iteration: 1\n",
      "  trial_id: b15f3_00001\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 10.3/31.2 GiB<br>PopulationBasedTraining: 1 checkpoints, 0 perturbs<br>Resources requested: 1/12 CPUs, 1/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (1 PAUSED, 1 PENDING, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc                 </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th><th style=\"text-align: right;\">  avg_val_loss</th><th style=\"text-align: right;\">  avg_val_accuracy</th><th style=\"text-align: right;\">  training_iteration</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>PAUSED  </td><td>                    </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.152378</td><td style=\"text-align: right;\">          0.93884 </td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>RUNNING </td><td>192.168.100.11:18265</td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.143292</td><td style=\"text-align: right;\">          0.941801</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>PENDING </td><td>                    </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">              </td><td style=\"text-align: right;\">                  </td><td style=\"text-align: right;\">                    </td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m 2020-09-28 20:52:18,592\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "\u001b[2m\u001b[36m(pid=18265)\u001b[0m 2020-09-28 20:52:19,263\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m   warnings.warn(msg, UserWarning)\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:959: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-75b20c2c956a2698fe577f5543d206ff04587b8d-0100.out' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:963: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-75b20c2c956a2698fe577f5543d206ff04587b8d-0100.err' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m GPU available: True, used: True\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m TPU available: False, using: 0 TPU cores\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m CUDA_VISIBLE_DEVICES: [0]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m trial_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m global step:  0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m   | Name  | Type             | Params\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m -------------------------------------------\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m 0 | model | Unet             | 31 M  \n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m 1 | CE    | CrossEntropyLoss | 0     \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/checkpoint_591/checkpoint\n",
      "Result for DEFAULT_b15f3_00002:\n",
      "  avg_val_accuracy: 0.9436744524411892\n",
      "  avg_val_loss: 0.1384296715259552\n",
      "  date: 2020-09-28_20-58-20\n",
      "  done: false\n",
      "  experiment_id: 838780bf582c46f0869cc7890a2dd7d0\n",
      "  experiment_tag: '2'\n",
      "  hostname: lx9-304-12646\n",
      "  iterations_since_restore: 1\n",
      "  node_ip: 192.168.100.11\n",
      "  pid: 18259\n",
      "  should_checkpoint: true\n",
      "  time_since_restore: 358.9042401313782\n",
      "  time_this_iter_s: 358.9042401313782\n",
      "  time_total_s: 358.9042401313782\n",
      "  timestamp: 1601315900\n",
      "  timesteps_since_restore: 0\n",
      "  training_iteration: 1\n",
      "  trial_id: b15f3_00002\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 11.3/31.2 GiB<br>PopulationBasedTraining: 2 checkpoints, 0 perturbs<br>Resources requested: 1/12 CPUs, 1/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (2 PAUSED, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc                 </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th><th style=\"text-align: right;\">  avg_val_loss</th><th style=\"text-align: right;\">  avg_val_accuracy</th><th style=\"text-align: right;\">  training_iteration</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>PAUSED  </td><td>                    </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.152378</td><td style=\"text-align: right;\">          0.93884 </td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>PAUSED  </td><td>                    </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.143292</td><td style=\"text-align: right;\">          0.941801</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>RUNNING </td><td>192.168.100.11:18259</td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.13843 </td><td style=\"text-align: right;\">          0.943674</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m 2020-09-28 20:58:21,314\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "2020-09-28 20:58:22,054\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "\u001b[2m\u001b[36m(pid=18259)\u001b[0m 2020-09-28 20:58:22,056\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "2020-09-28 20:58:22,369\tWARNING util.py:137 -- The `start_trial` operation took 0.7357301712036133 seconds to complete, which may be a performance bottleneck.\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   warnings.warn(msg, UserWarning)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:959: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-a6cdb9bf20fd06d8776d78666e677fdb49e97026-0100.out' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:963: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-a6cdb9bf20fd06d8776d78666e677fdb49e97026-0100.err' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m 2020-09-28 20:58:25,526\tINFO trainable.py:473 -- Restored on 192.168.100.11 from checkpoint: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/checkpoint_tmp41745a/./\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m 2020-09-28 20:58:25,526\tINFO trainable.py:480 -- Current state after restoring: {'_iteration': 1, '_timesteps_total': None, '_time_total': 354.32049775123596, '_episodes_total': None}\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m GPU available: True, used: True\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m TPU available: False, using: 0 TPU cores\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m CUDA_VISIBLE_DEVICES: [0]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m trial_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m 2020-09-28 20:58:26,015\tERROR function_runner.py:230 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     return torch.load(path_or_url, map_location=map_location)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     with _open_file_like(f, 'rb') as opened_file:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     return _open_file(name_or_buffer, mode)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     super(_open_file, self).__init__(open(name, mode))\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/checkpoint_tmp41745a/./'\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 243, in run\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     return torch.load(path_or_url, map_location=map_location)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     with _open_file_like(f, 'rb') as opened_file:\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     return _open_file(name_or_buffer, mode)\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m     super(_open_file, self).__init__(open(name, mode))\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/checkpoint_tmp41745a/./'\n",
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m \n",
      "2020-09-28 20:58:26,156\tERROR trial_runner.py:523 -- Trial DEFAULT_b15f3_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 471, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 430, in fetch_result\n",
      "    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/worker.py\", line 1538, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18263, ip=192.168.100.11)\n",
      "  File \"python/ray/_raylet.pyx\", line 479, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 432, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/trainable.py\", line 332, in train\n",
      "    result = self.step()\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 337, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 456, in _report_thread_runner_error\n",
      "    .format(err_tb_str)))\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18263, ip=192.168.100.11)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "    output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "  File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "    checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "    return torch.load(path_or_url, map_location=map_location)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "    with _open_file_like(f, 'rb') as opened_file:\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "    return _open_file(name_or_buffer, mode)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "    super(_open_file, self).__init__(open(name, mode))\n",
      "IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/checkpoint_tmp41745a/./'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18263)\u001b[0m chekpoint_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/checkpoint_tmp41745a/./\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 10.7/31.2 GiB<br>PopulationBasedTraining: 2 checkpoints, 0 perturbs<br>Resources requested: 0/12 CPUs, 0/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (1 ERROR, 2 PAUSED)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th><th style=\"text-align: right;\">  avg_val_loss</th><th style=\"text-align: right;\">  avg_val_accuracy</th><th style=\"text-align: right;\">  training_iteration</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.152378</td><td style=\"text-align: right;\">          0.93884 </td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>PAUSED  </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.143292</td><td style=\"text-align: right;\">          0.941801</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>PAUSED  </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.13843 </td><td style=\"text-align: right;\">          0.943674</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                       </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td style=\"text-align: right;\">           1</td><td>/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   warnings.warn(msg, UserWarning)\n",
      "2020-09-28 20:58:26,585\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "2020-09-28 20:58:26,927\tWARNING util.py:137 -- The `start_trial` operation took 0.7484328746795654 seconds to complete, which may be a performance bottleneck.\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:959: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-613a75b75d5a3029b2dd2831cc9bc958f5749234-0100.out' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:963: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-613a75b75d5a3029b2dd2831cc9bc958f5749234-0100.err' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m 2020-09-28 20:58:29,325\tINFO trainable.py:473 -- Restored on 192.168.100.11 from checkpoint: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/checkpoint_tmpf21a36/./\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m 2020-09-28 20:58:29,326\tINFO trainable.py:480 -- Current state after restoring: {'_iteration': 1, '_timesteps_total': None, '_time_total': 351.2957224845886, '_episodes_total': None}\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m GPU available: True, used: True\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m TPU available: False, using: 0 TPU cores\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m CUDA_VISIBLE_DEVICES: [0]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m trial_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m 2020-09-28 20:58:29,752\tERROR function_runner.py:230 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     return torch.load(path_or_url, map_location=map_location)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     with _open_file_like(f, 'rb') as opened_file:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     return _open_file(name_or_buffer, mode)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     super(_open_file, self).__init__(open(name, mode))\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/checkpoint_tmpf21a36/./'\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 243, in run\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     return torch.load(path_or_url, map_location=map_location)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     with _open_file_like(f, 'rb') as opened_file:\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     return _open_file(name_or_buffer, mode)\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m     super(_open_file, self).__init__(open(name, mode))\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/checkpoint_tmpf21a36/./'\n",
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m \n",
      "2020-09-28 20:58:29,948\tERROR trial_runner.py:523 -- Trial DEFAULT_b15f3_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 471, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 430, in fetch_result\n",
      "    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/worker.py\", line 1538, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18261, ip=192.168.100.11)\n",
      "  File \"python/ray/_raylet.pyx\", line 479, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 432, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/trainable.py\", line 332, in train\n",
      "    result = self.step()\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 337, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 456, in _report_thread_runner_error\n",
      "    .format(err_tb_str)))\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18261, ip=192.168.100.11)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "    output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "  File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "    checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "    return torch.load(path_or_url, map_location=map_location)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "    with _open_file_like(f, 'rb') as opened_file:\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "    return _open_file(name_or_buffer, mode)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "    super(_open_file, self).__init__(open(name, mode))\n",
      "IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/checkpoint_tmpf21a36/./'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18261)\u001b[0m chekpoint_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/checkpoint_tmpf21a36/./\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:124: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   warnings.warn(msg, UserWarning)\n",
      "2020-09-28 20:58:30,402\tINFO trainable.py:85 -- Checkpoint size is 512436057 bytes\n",
      "2020-09-28 20:58:30,703\tWARNING util.py:137 -- The `start_trial` operation took 0.7478828430175781 seconds to complete, which may be a performance bottleneck.\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:959: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-730d724c952e19e7ed2fa05e6341f2ee93e0234a-0100.out' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m /home/leos/.local/lib/python3.6/site-packages/ray/worker.py:963: ResourceWarning:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2020-09-28_20-40-25_241641_18184/logs/worker-730d724c952e19e7ed2fa05e6341f2ee93e0234a-0100.err' mode='a' encoding='utf-8'>\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 11.0/31.2 GiB<br>PopulationBasedTraining: 2 checkpoints, 0 perturbs<br>Resources requested: 1/12 CPUs, 1/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (2 ERROR, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th><th style=\"text-align: right;\">  avg_val_loss</th><th style=\"text-align: right;\">  avg_val_accuracy</th><th style=\"text-align: right;\">  training_iteration</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.152378</td><td style=\"text-align: right;\">          0.93884 </td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.143292</td><td style=\"text-align: right;\">          0.941801</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.13843 </td><td style=\"text-align: right;\">          0.943674</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 2<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                       </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td style=\"text-align: right;\">           1</td><td>/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/error.txt</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td style=\"text-align: right;\">           1</td><td>/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m trial_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m 2020-09-28 20:58:33,082\tINFO trainable.py:473 -- Restored on 192.168.100.11 from checkpoint: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/checkpoint_tmp94e63a/./\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m 2020-09-28 20:58:33,082\tINFO trainable.py:480 -- Current state after restoring: {'_iteration': 1, '_timesteps_total': None, '_time_total': 358.9042401313782, '_episodes_total': None}\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m GPU available: True, used: True\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m TPU available: False, using: 0 TPU cores\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m CUDA_VISIBLE_DEVICES: [0]\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m 2020-09-28 20:58:33,514\tERROR function_runner.py:230 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     return torch.load(path_or_url, map_location=map_location)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     with _open_file_like(f, 'rb') as opened_file:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     return _open_file(name_or_buffer, mode)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     super(_open_file, self).__init__(open(name, mode))\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/checkpoint_tmp94e63a/./'\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 243, in run\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     return torch.load(path_or_url, map_location=map_location)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     with _open_file_like(f, 'rb') as opened_file:\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     return _open_file(name_or_buffer, mode)\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m   File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m     super(_open_file, self).__init__(open(name, mode))\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/checkpoint_tmp94e63a/./'\n",
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m \n",
      "2020-09-28 20:58:33,703\tERROR trial_runner.py:523 -- Trial DEFAULT_b15f3_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 471, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 430, in fetch_result\n",
      "    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/worker.py\", line 1538, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18266, ip=192.168.100.11)\n",
      "  File \"python/ray/_raylet.pyx\", line 479, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 432, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/trainable.py\", line 332, in train\n",
      "    result = self.step()\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 337, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 456, in _report_thread_runner_error\n",
      "    .format(err_tb_str)))\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18266, ip=192.168.100.11)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 224, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 287, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 509, in _trainable_func\n",
      "    output = train_func(config, checkpoint_dir=checkpoint_dir)\n",
      "  File \"/home/local/leos/Dippa/src/tune/tune_experiment.py\", line 76, in train_tune_checkpoint\n",
      "    checkpoint = pl_load(checkpoint_dir, map_location=lambda storage, loc: storage)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py\", line 9, in load\n",
      "    return torch.load(path_or_url, map_location=map_location)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 525, in load\n",
      "    with _open_file_like(f, 'rb') as opened_file:\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 212, in _open_file_like\n",
      "    return _open_file(name_or_buffer, mode)\n",
      "  File \"/home/leos/.local/lib/python3.6/site-packages/torch/serialization.py\", line 193, in __init__\n",
      "    super(_open_file, self).__init__(open(name, mode))\n",
      "IsADirectoryError: [Errno 21] Is a directory: '/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/checkpoint_tmp94e63a/./'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18266)\u001b[0m chekpoint_dir:  /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/checkpoint_tmp94e63a/./\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 11.1/31.2 GiB<br>PopulationBasedTraining: 2 checkpoints, 0 perturbs<br>Resources requested: 0/12 CPUs, 0/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects (0/1.0 GPUType:RTX)<br>Result logdir: /home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt<br>Number of trials: 3 (3 ERROR)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  edge_weight</th><th style=\"text-align: right;\">   lr</th><th style=\"text-align: right;\">  batch_size</th><th style=\"text-align: right;\">  avg_val_loss</th><th style=\"text-align: right;\">  avg_val_accuracy</th><th style=\"text-align: right;\">  training_iteration</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.152378</td><td style=\"text-align: right;\">          0.93884 </td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.143292</td><td style=\"text-align: right;\">          0.941801</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">            1</td><td style=\"text-align: right;\">0.001</td><td style=\"text-align: right;\">           6</td><td style=\"text-align: right;\">      0.13843 </td><td style=\"text-align: right;\">          0.943674</td><td style=\"text-align: right;\">                   1</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 3<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name         </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                       </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DEFAULT_b15f3_00000</td><td style=\"text-align: right;\">           1</td><td>/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_0_2020-09-28_20-40-264ejlxunr/error.txt</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00001</td><td style=\"text-align: right;\">           1</td><td>/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_1_2020-09-28_20-46-23ry4ciw80/error.txt</td></tr>\n",
       "<tr><td>DEFAULT_b15f3_00002</td><td style=\"text-align: right;\">           1</td><td>/home/local/leos/Dippa/results/tests/Unet/version_test_pannuke_unet_pbt6/tune_pbt/DEFAULT_2_2020-09-28_20-52-18rkpm56d7/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [DEFAULT_b15f3_00000, DEFAULT_b15f3_00001, DEFAULT_b15f3_00002])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-07edf2c64b25>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mconfig\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mCONFIG\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0manalysis\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtune_pbt\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum_samples\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum_epochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgpus_per_trial\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnotebook\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/home/local/leos/Dippa/src/tune/tune_experiment.py\u001b[0m in \u001b[0;36mtune_pbt\u001b[0;34m(conf, num_samples, num_epochs, gpus_per_trial, notebook)\u001b[0m\n\u001b[1;32m    141\u001b[0m         \u001b[0mprogress_reporter\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mreporter\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    142\u001b[0m         \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"tune_pbt\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 143\u001b[0;31m         \u001b[0mlocal_dir\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mPath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mRESULT_DIR\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mmn\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;34mf\"version_{ev}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    144\u001b[0m     )\n\u001b[1;32m    145\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.6/site-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, stop, config, resources_per_trial, num_samples, local_dir, upload_dir, trial_name_creator, loggers, sync_to_cloud, sync_to_driver, checkpoint_freq, checkpoint_at_end, sync_on_checkpoint, keep_checkpoints_num, checkpoint_score_attr, global_checkpoint_period, export_formats, max_failures, fail_fast, restore, search_alg, scheduler, with_server, server_port, verbose, progress_reporter, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, return_trials, ray_auto_init)\u001b[0m\n\u001b[1;32m    354\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    355\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 356\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    357\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    358\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [DEFAULT_b15f3_00000, DEFAULT_b15f3_00001, DEFAULT_b15f3_00002])"
     ]
    }
   ],
   "source": [
    "config = CONFIG\n",
    "analysis = tune_pbt(config, num_samples=3, num_epochs=3, gpus_per_trial=1, notebook=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
